//! Screen effects: short animated stickers a viewer sends to everyone watching a
//! screen share.
//!
//! - `manifest`: caps and validation, shared with `build.rs`.
//! - The effect table (`EFFECTS`) is generated at build time from
//!   `resources/effects/effects.toml`; every asset is compiled in.
//! - `wire`: the data-channel packet (id only) and its validation.
//! - `player`: one-at-a-time playback that streams frames from a worker thread.
//!
//! Rendering lives in `graphics::effect_renderer`. Author docs:
//! `resources/effects/effects.md`.

pub mod manifest;
pub mod player;
pub mod wire;

/// One compiled-in effect. Generated by `build.rs`; all metadata was checked
/// against the caps in `manifest` when the binary was built.
#[derive(Debug)]
pub struct EffectDef {
    /// Wire id, `^[a-z0-9_]{1,32}$`.
    pub id: &'static str,
    /// Picker tooltip.
    pub label: &'static str,
    /// Times the frames play (1..=3).
    pub loops: u32,
    /// On-screen height as a fraction of the shared screen's height.
    pub height_fraction: f64,
    /// Canvas size in pixels.
    pub width: u32,
    pub height: u32,
    /// Per-frame delays in ms, in file order.
    pub delays_ms: &'static [u32],
    /// The compressed animated WebP.
    pub bytes: &'static [u8],
    /// `THUMBNAIL_EDGE`² straight RGBA picker thumbnail.
    pub thumbnail: &'static [u8],
}

impl EffectDef {
    /// Duration of one pass through the frames.
    pub fn loop_ms(&self) -> u64 {
        self.delays_ms.iter().map(|&delay| delay as u64).sum()
    }

    /// Total play time (`loops` passes).
    pub fn total_ms(&self) -> u64 {
        self.loop_ms() * self.loops as u64
    }
}

include!(concat!(env!("OUT_DIR"), "/effects_gen.rs"));

/// Looks up a compiled-in effect by wire id.
pub fn find(id: &str) -> Option<&'static EffectDef> {
    EFFECTS.iter().find(|effect| effect.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_effects_decode_to_their_build_time_metadata() {
        assert!(!EFFECTS.is_empty());
        for effect in EFFECTS {
            let info = manifest::inspect_asset(effect.bytes)
                .unwrap_or_else(|e| panic!("{}: {e}", effect.id));
            assert_eq!((info.width, info.height), (effect.width, effect.height));
            assert_eq!(info.delays_ms, effect.delays_ms, "{}", effect.id);
            assert!(effect.total_ms() <= manifest::MAX_TOTAL_MS as u64);
            assert!(effect.height_fraction <= manifest::MAX_HEIGHT_FRACTION);
            assert_eq!(
                effect.thumbnail.len(),
                (manifest::THUMBNAIL_EDGE * manifest::THUMBNAIL_EDGE * 4) as usize
            );
            assert_eq!(find(effect.id).map(|e| e.id), Some(effect.id));
        }
        assert!(find("no_such_effect").is_none());
    }
}
