use std::env;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

#[path = "src/effects/manifest.rs"]
mod manifest;

fn main() {
    build_effects();

    println!("cargo:rerun-if-env-changed=HOPP_CORE_BIN_DEFAULT");
    let is_default = env::var("HOPP_CORE_BIN_DEFAULT").unwrap_or("0".to_string()) == "1";
    let binary_name = if is_default {
        "hopp_core"
    } else {
        let target = env::var("TARGET").unwrap();
        match target.as_str() {
            "x86_64-apple-darwin" => "hopp_core-x86_64-apple-darwin",
            "aarch64-apple-darwin" => "hopp_core-aarch64-apple-darwin",
            "aarch64-pc-windows-msvc" => "hopp_core-aarch64-pc-windows-msvc",
            "x86_64-pc-windows-msvc" => "hopp_core-x86_64-pc-windows-msvc",
            "aarch64-unknown-linux-gnu" => "hopp_core-aarch64-unknown-linux-gnu",
            "x86_64-unknown-linux-gnu" => "hopp_core-x86_64-unknown-linux-gnu",
            _ => "hopp_core",
        }
    };

    let profile = env::var("PROFILE").unwrap();
    let output_dir = if profile == "release" {
        "target/release"
    } else {
        "target/debug"
    };

    let target = env::var("TARGET").unwrap();
    if target.contains("windows") {
        // Windows uses /OUT:filename.exe
        let binary_name = format!("{binary_name}.exe");
        println!("cargo:rustc-link-arg-bin=hopp_core=/OUT:{output_dir}/{binary_name}");
    } else {
        // Unix systems use -o filename
        println!("cargo:rustc-link-arg-bin=hopp_core=-o");
        println!("cargo:rustc-link-arg-bin=hopp_core={output_dir}/{binary_name}");
    }
}

/// Validates `resources/effects/effects.toml` and every asset it names (every frame
/// is decoded), then writes `$OUT_DIR/effects_gen.rs` with the compiled-in table and
/// a picker thumbnail per effect. Any rule violation fails the build.
fn build_effects() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let effects_dir = manifest_dir.join("resources").join("effects");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_path = effects_dir.join("effects.toml");

    println!("cargo:rerun-if-changed=src/effects/manifest.rs");
    println!("cargo:rerun-if-changed={}", effects_dir.display());
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let text = std::fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("effects: cannot read {}: {e}", manifest_path.display()));
    let parsed = toml::from_str::<manifest::Manifest>(&text)
        .map_err(|e| vec![manifest::parse_error(e)])
        .and_then(|parsed| {
            for entry in &parsed.effects {
                if manifest::is_valid_file_name(&entry.file) {
                    println!(
                        "cargo:rerun-if-changed={}",
                        effects_dir.join(&entry.file).display()
                    );
                }
            }
            manifest::validate(&parsed, |file| {
                std::fs::read(effects_dir.join(file)).map_err(|e| e.to_string())
            })
        });
    let effects = match parsed {
        Ok(effects) => effects,
        Err(errors) => {
            let mut report = format!(
                "\n\nInvalid screen effects in {} ({} error(s)):\n",
                manifest_path.display(),
                errors.len()
            );
            for error in &errors {
                let _ = writeln!(report, "  - {error}");
            }
            report.push_str("See core/resources/effects/effects.md for the rules.\n");
            panic!("{report}");
        }
    };

    let mut code = String::from(
        "// @generated by build.rs from resources/effects/effects.toml. Do not edit.\n\
         pub static EFFECTS: &[EffectDef] = &[\n",
    );
    for effect in &effects {
        let asset_path = effects_dir.join(&effect.file);
        let bytes = std::fs::read(&asset_path).unwrap();
        let thumbnail = manifest::thumbnail_rgba(&bytes, effect.thumbnail_frame)
            .unwrap_or_else(|e| panic!("effects: thumbnail for {}: {e}", effect.id));
        let thumbnail_path = out_dir.join(format!("effect_thumb_{}.rgba", effect.id));
        std::fs::write(&thumbnail_path, thumbnail).unwrap();

        let delays = effect
            .asset
            .delays_ms
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(
            code,
            "    EffectDef {{\n\
             \x20       id: {id:?},\n\
             \x20       label: {label:?},\n\
             \x20       loops: {loops},\n\
             \x20       height_fraction: {fraction:?},\n\
             \x20       width: {width},\n\
             \x20       height: {height},\n\
             \x20       delays_ms: &[{delays}],\n\
             \x20       bytes: include_bytes!({asset:?}),\n\
             \x20       thumbnail: include_bytes!({thumb:?}),\n\
             \x20   }},\n",
            id = effect.id,
            label = effect.label,
            loops = effect.loops,
            fraction = effect.height_fraction,
            width = effect.asset.width,
            height = effect.asset.height,
            asset = path_str(&asset_path),
            thumb = path_str(&thumbnail_path),
        );
    }
    code.push_str("];\n");
    std::fs::write(out_dir.join("effects_gen.rs"), code).unwrap();
}

fn path_str(path: &Path) -> String {
    path.to_str()
        .unwrap_or_else(|| panic!("effects: non-UTF-8 path {}", path.display()))
        .to_string()
}
