use serde::{Deserialize, Serialize};
use std::fmt;
use std::fs;
use std::io::{Read, Write};
use std::path::Path;
use std::sync::mpsc;
use std::sync::{Arc, Mutex};

pub mod client;

/// Identifies a request sent by Tauri; core echoes it on the matching response.
pub type RequestId = u64;

/// Identifies one call (generated by the frontend, opaque to core and Tauri).
/// `CallStart`, `CallStartResult`, `CallEnd`, `CallEnded` and `RoomConnectionFailed` carry it
/// so a message about an old call can never tear down a newer one.
pub type CallId = u64;

/// Frames larger than this are treated as a corrupt stream.
pub const MAX_FRAME_BYTES: u64 = 64 * 1024 * 1024;

// Platform-specific imports
#[cfg(unix)]
use std::os::unix::net::{UnixListener, UnixStream};

#[cfg(windows)]
use std::net::{TcpListener, TcpStream};

#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable, Serialize, Deserialize)]
pub struct Extent {
    pub width: f64,
    pub height: f64,
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy)]
pub enum ScreenShareResolution {
    P1080,
    P1440,
    P4K,
}

#[derive(Debug, Default, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
pub enum ScreenSharePickerMode {
    #[default]
    Screen,
    Window,
}

impl ScreenShareResolution {
    pub fn extent(self) -> Extent {
        match self {
            ScreenShareResolution::P1080 => Extent {
                width: 1920.0,
                height: 1080.0,
            },
            ScreenShareResolution::P1440 => Extent {
                width: 2560.0,
                height: 1440.0,
            },
            ScreenShareResolution::P4K => Extent {
                width: 4096.0,
                height: 2160.0,
            },
        }
    }
}

#[derive(Debug, Serialize, Deserialize)]
pub struct WindowFrameMessage {
    pub origin_x: f64,
    pub origin_y: f64,
    pub width: f64,
    pub height: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CursorPositionMessage {
    pub x: f32,
    pub y: f32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MouseClickMessage {
    pub x: f32,
    pub y: f32,
    pub button: u32,
    pub clicks: f32,
    pub shift_key: bool,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ScrollMessage {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct KeystrokeMessage {
    pub key: String,
    pub meta: bool,
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub down: bool,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy)]
pub enum ContentType {
    Display,
    Window,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy)]
pub struct Content {
    pub content_type: ContentType,
    pub id: u32,
}

impl fmt::Display for Content {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.content_type {
            ContentType::Display => write!(f, "Display {}", self.id),
            ContentType::Window => write!(f, "Window {}", self.id),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ScreenShareMessage {
    pub content: Content,
    pub resolution: Extent,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CallStartMessage {
    pub call_id: CallId,
    pub audio_token: String,
    pub video_token: String,
    pub audio_device_name: String,
    pub start_mic_on_call: Option<bool>,
    pub start_camera_on_call: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CallStartResultMessage {
    pub call_id: CallId,
    pub result: Result<(), String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct RoomConnectionFailedMessage {
    pub call_id: CallId,
    pub reason: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SentryMetadata {
    pub user_id: String,
    pub app_version: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DrawingEnabled {
    pub permanent: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AudioDevice {
    pub name: String,
    pub default: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AudioCaptureMessage {
    pub device_name: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CameraDevice {
    pub name: String,
    // Camera index now is not stable, the `stable_id` is not yet released.
    // For now we will use the camera name as the id and hope for a new release and
    // no duplicate names 🤞:
    // https://github.com/l1npengtul/nokhwa/blob/ab2bedfbf13dfed4fabe77dcf725012fcaa4d305/nokhwa-core/src/types.rs#L478-L480
    pub id: String,
    pub default: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CameraStartMessage {
    /// Camera to open. `None` means core's cached preferred camera (see
    /// `Message::SetPreferredCamera`), falling back to the system default.
    pub device_name: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CoreParticipantState {
    pub identity: String,
    pub name: String,
    pub connected: bool,
    pub muted: bool,
    pub has_camera: bool,
    pub is_screensharing: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub enum CoreRoleChange {
    Sharer,
    Controller,
    None,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct CoreRoleEvent {
    pub role: CoreRoleChange,
}

/// Low-bandwidth mode state for the current call, sent from core to the UI.
/// The mode is active while any participant (local or remote) requests it.
#[derive(Debug, Serialize, Deserialize, Clone, Default, PartialEq)]
pub struct BandwidthModeState {
    pub active: bool,
    pub local_requested: bool,
    /// Display names of the remote participants currently requesting the mode.
    pub requested_by: Vec<String>,
}

/// Represents the user's preferred interaction mode for screen sharing sessions.
/// This is stored persistently and restored when the user joins a new session.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type")]
pub enum StoredMode {
    /// Remote control mode - mouse and keyboard events are forwarded to the sharer
    RemoteControl,
    /// Click animation mode - clicks are visualized on the shared screen
    ClickAnimation,
    /// Drawing mode - freehand drawing on the shared screen
    Draw {
        /// If true, drawings persist until manually cleared; if false, they auto-expire
        permanent: bool,
    },
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Message {
    GetAvailableContent,
    /// Request (has a response).
    CallStart(CallStartMessage),
    /// Response to `CallStart`.
    CallStartResult(CallStartResultMessage),
    /// End the call with this id. `None` ends whatever call is active (used on quit).
    /// A `CallEnd` for a call that is not the active one is ignored by core, apart from
    /// the `CallEnded` echo.
    CallEnd(Option<CallId>),
    StartScreenShare(ScreenShareMessage),
    StartScreenShareResult(Result<(), String>),
    StopScreenshare,
    Ping,
    ControllerCursorEnabled(bool),
    LivekitServerUrl(String),
    SentryMetadata(SentryMetadata),
    DrawingEnabled(DrawingEnabled),
    ListAudioDevices,
    AudioDeviceList(Vec<AudioDevice>),
    StartAudioCapture(AudioCaptureMessage),
    StartAudioCaptureResult(Result<(), String>),
    StopAudioCapture,
    MuteAudio,
    UnmuteAudio,
    ListCameras,
    CameraList(Vec<CameraDevice>),
    /// Request (has a response) when sent with a request id; fire-and-forget otherwise.
    StartCamera(CameraStartMessage),
    StartCameraResult(Result<(), String>),
    StopCamera,
    CameraFailed(String),
    OpenCamera,
    OpenScreensharing,
    ToggleMic,
    OpenScreenShareWindow,
    CloseScreenShareWindow,
    OpenStatsWindow,
    BringWindowsToFront,
    BringWindowsToFrontResult(bool),
    /// Tauri → core: camera to use when a start-camera request names none. Sent at
    /// startup and whenever the user's last-used camera changes.
    SetPreferredCamera(Option<String>),
    // Core → Tauri event forwarding
    ParticipantsSnapshot(Vec<CoreParticipantState>),
    RoleChange(CoreRoleEvent),
    /// Core → Tauri: the call with this id was torn down (from `CallEnd`, or hang-up in a
    /// core window). `None` only when core had no call id.
    CallEnded(Option<CallId>),
    RoomConnectionFailed(RoomConnectionFailedMessage),
    /// App Veil could not be initialized; protected apps may be visible while sharing.
    AppVeilFailed(String),
    ControllerDrawPersistChanged(bool),
    SharerDrawPersistChanged(bool),
    LastModeChanged(StoredMode),
    ActiveMicChanged(String),
    ActiveCameraChanged(String),
    DrawingDisabled,
    ExitRequested,
    SetNoiseCancellation(bool),
    SetScreenShareResolution(ScreenShareResolution),
    SetScreenSharePickerMode(ScreenSharePickerMode),
    SetAppVeilBundleIds(Vec<String>),
    SetTelemetryEnabled(bool),
    /// Microphone RMS level in [0.0, 1.0], emitted ~1 Hz from core capturer.
    MicrophoneAudioLevel(f32),
    /// Persisted default: request low-bandwidth mode in every call joined.
    SetLowBandwidthDefault(bool),
    /// Request (or withdraw the request for) low-bandwidth mode in the current call.
    SetCallLowBandwidth(bool),
    BandwidthModeState(BandwidthModeState),
}

/// Wire unit: a message plus the request id it belongs to.
///
/// Tauri sets `request_id` on requests; core copies it onto the response. Events in either
/// direction have no id. Unknown ids on the receiving side are discarded (a response that
/// arrives after its request timed out).
#[derive(Debug, Serialize, Deserialize)]
pub struct Frame {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<RequestId>,
    pub message: Message,
}

impl Frame {
    pub fn event(message: Message) -> Self {
        Self {
            request_id: None,
            message,
        }
    }

    pub fn with_id(request_id: Option<RequestId>, message: Message) -> Self {
        Self {
            request_id,
            message,
        }
    }
}

// Platform-specific stream type alias
#[cfg(unix)]
type Stream = UnixStream;
#[cfg(windows)]
type Stream = TcpStream;

/// Send half of the socket. Clone-safe via Arc<Mutex<Stream>>.
#[derive(Clone)]
pub struct SocketSender {
    stream: Arc<Mutex<Stream>>,
}

impl SocketSender {
    /// Sends an event (no request id).
    pub fn send(&self, message: Message) -> Result<(), std::io::Error> {
        self.send_frame(&Frame::event(message))
    }

    /// Sends `message` tagged with `request_id` (a response when replying to a request).
    /// With `None` this is the same as [`SocketSender::send`].
    pub fn send_with_id(
        &self,
        request_id: Option<RequestId>,
        message: Message,
    ) -> Result<(), std::io::Error> {
        self.send_frame(&Frame::with_id(request_id, message))
    }

    pub fn send_frame(&self, frame: &Frame) -> Result<(), std::io::Error> {
        let bytes = encode_frame(frame)?;
        let mut stream = self.stream.lock().unwrap_or_else(|e| e.into_inner());
        stream.write_all(&bytes)?;
        Ok(())
    }

    /// Shuts the connection down in both directions. Blocked readers on either end
    /// see end-of-stream.
    pub fn shutdown(&self) {
        use std::net::Shutdown;
        let stream = self.stream.lock().unwrap_or_else(|e| e.into_inner());
        let _ = stream.shutdown(Shutdown::Both);
    }
}

fn encode_frame(frame: &Frame) -> Result<Vec<u8>, std::io::Error> {
    let payload = serde_json::to_vec(frame)?;
    let mut bytes = Vec::with_capacity(8 + payload.len());
    bytes.extend_from_slice(&(payload.len() as u64).to_le_bytes());
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

enum ReadError {
    /// The stream is closed or corrupt; nothing more can be read.
    Io(std::io::Error),
    /// A whole frame was read but did not decode (e.g. an unknown variant). The stream
    /// is still in sync, so the reader skips it.
    Decode(serde_json::Error),
}

fn read_frame(stream: &mut impl Read) -> Result<Frame, ReadError> {
    let mut size_buffer = [0u8; 8];
    stream.read_exact(&mut size_buffer).map_err(ReadError::Io)?;
    let size = u64::from_le_bytes(size_buffer);
    if size > MAX_FRAME_BYTES {
        return Err(ReadError::Io(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("frame of {size} bytes exceeds the {MAX_FRAME_BYTES} byte limit"),
        )));
    }
    let mut payload = vec![0u8; size as usize];
    stream.read_exact(&mut payload).map_err(ReadError::Io)?;
    serde_json::from_slice(&payload).map_err(ReadError::Decode)
}

/// Receive half: owns a background reader thread that decodes frames in wire order into
/// `incoming`. Dropping this struct shuts the stream down, which unblocks the reader
/// (it sees end-of-stream) and closes `incoming`.
pub struct EventSocket {
    pub incoming: mpsc::Receiver<Frame>,
    stream: Stream,
}

impl EventSocket {
    fn new(mut read_stream: Stream, shutdown_stream: Stream) -> Self {
        let (incoming_tx, incoming_rx) = mpsc::channel();

        log::info!("EventSocket: spawning background reader thread");
        std::thread::spawn(move || {
            // No read timeout: a timeout in the middle of a frame would desync the
            // length-prefixed stream. Shutdown (drop of EventSocket / SocketSender::shutdown)
            // unblocks the read instead.
            let _ = read_stream.set_read_timeout(None);
            loop {
                match read_frame(&mut read_stream) {
                    Ok(frame) => {
                        if incoming_tx.send(frame).is_err() {
                            log::info!("Background reader: channel closed, stopping");
                            break;
                        }
                    }
                    Err(ReadError::Decode(e)) => {
                        log::error!("Background reader: skipping undecodable frame: {e}");
                    }
                    Err(ReadError::Io(e)) if e.kind() == std::io::ErrorKind::Interrupted => {}
                    Err(ReadError::Io(e)) => {
                        if e.kind() == std::io::ErrorKind::UnexpectedEof {
                            log::info!("Background reader: stream closed");
                        } else {
                            log::error!("Background reader: IO error: {e:?}");
                        }
                        break;
                    }
                }
            }
            log::info!("Background reader: thread exiting");
        });

        Self {
            incoming: incoming_rx,
            stream: shutdown_stream,
        }
    }

    /// Takes the incoming receiver, leaving a closed one behind. The EventSocket must
    /// be kept alive while the receiver is used (dropping it shuts the stream down).
    pub fn take_incoming(&mut self) -> mpsc::Receiver<Frame> {
        let (_tx, dummy_rx) = mpsc::channel();
        std::mem::replace(&mut self.incoming, dummy_rx)
    }
}

impl Drop for EventSocket {
    fn drop(&mut self) {
        log::info!("EventSocket: shutting down");
        use std::net::Shutdown;
        let _ = self.stream.shutdown(Shutdown::Both);
        log::info!("EventSocket: shutdown complete");
    }
}

fn build_pair(stream: Stream) -> std::io::Result<(SocketSender, EventSocket)> {
    let write_stream = stream.try_clone()?;
    let read_stream = stream.try_clone()?;
    let shutdown_stream = stream;

    let sender = SocketSender {
        stream: Arc::new(Mutex::new(write_stream)),
    };

    let event_socket = EventSocket::new(read_stream, shutdown_stream);

    Ok((sender, event_socket))
}

/// Connect to an existing socket (client side).
pub fn connect(socket_path: &str) -> Result<(SocketSender, EventSocket), std::io::Error> {
    log::info!("Connecting to socket at {socket_path}");
    #[cfg(unix)]
    let stream = {
        let stream = UnixStream::connect(socket_path)?;
        stream.set_read_timeout(None)?;
        stream
    };

    #[cfg(windows)]
    let stream = {
        let port = socket_path_to_port(socket_path);
        let addr = format!("127.0.0.1:{port}");
        let stream = TcpStream::connect(addr)?;
        stream.set_read_timeout(None)?;
        stream
    };

    build_pair(stream)
}

/// Create a socket and wait for a client to connect (server side).
pub fn listen(socket_path: &str) -> Result<(SocketSender, EventSocket), std::io::Error> {
    log::info!("Creating socket at {socket_path}");
    #[cfg(unix)]
    let stream = {
        if Path::new(socket_path).exists() {
            fs::remove_file(socket_path)?;
        }

        let listener = UnixListener::bind(socket_path)?;
        listener.set_nonblocking(true)?;
        let mut stream = None;
        let times = if cfg!(debug_assertions) { 100 } else { 10 };
        for i in 0..times {
            log::info!("Waiting for client {i}/{times}");
            match listener.accept() {
                Ok((s, _)) => {
                    stream = Some(s);
                    break;
                }
                Err(_) => {
                    std::thread::sleep(std::time::Duration::from_secs(1));
                }
            }
        }
        let stream = stream.ok_or_else(|| {
            std::io::Error::other("Client did not connect after multiple attempts")
        })?;
        stream.set_nonblocking(false)?;
        log::info!("Client connected");
        stream.set_read_timeout(None)?;
        stream
    };

    #[cfg(windows)]
    let stream = {
        if Path::new(socket_path).exists() {
            fs::remove_file(socket_path)?;
        }

        // Get initial port to try
        let mut port = socket_path_to_port(socket_path);
        let mut listener = None;

        // Try to bind, incrementing port if necessary
        for try_num in 0..500 {
            let addr = format!("127.0.0.1:{port}");
            match TcpListener::bind(addr) {
                Ok(l) => {
                    listener = Some(l);
                    break;
                }
                Err(_) => {
                    log::info!("Port {port} is in use, trying next port...");
                    port += 1;
                    if try_num != 0 && try_num % 100 == 0 {
                        port += 100;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(10));
                }
            }
        }

        let listener = listener.ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::AddrInUse,
                "Could not find available port after multiple attempts",
            )
        })?;

        // Store just the port number in the file
        fs::write(socket_path, port.to_string())?;

        log::info!("Listening on port {port}, waiting for client");
        listener.set_nonblocking(true)?;
        let mut stream = None;
        let times = if cfg!(debug_assertions) { 100 } else { 50 };
        for i in 0..times {
            log::info!("Waiting for client {i}/{times}");
            match listener.accept() {
                Ok((s, _)) => {
                    stream = Some(s);
                    break;
                }
                Err(_) => {
                    std::thread::sleep(std::time::Duration::from_secs(1));
                }
            }
        }
        let stream = stream.ok_or_else(|| {
            std::io::Error::other("Client did not connect after multiple attempts")
        })?;
        stream.set_nonblocking(false)?;
        log::info!("Client connected");
        stream.set_read_timeout(None)?;
        stream
    };

    build_pair(stream)
}

#[cfg(windows)]
fn socket_path_to_port(socket_path: &str) -> u16 {
    // First try to read the port from the file
    if let Ok(content) = fs::read_to_string(socket_path) {
        if let Ok(port) = content.trim().parse::<u16>() {
            log::info!("Found port {port} in file {socket_path}");
            port
        } else {
            log::warn!("Could not parse port from file {socket_path}: '{content}'");
            calculate_port_from_hash(socket_path)
        }
    } else {
        log::debug!("Could not read port from file {socket_path}, calculating from hash");
        calculate_port_from_hash(socket_path)
    }
}

#[cfg(windows)]
fn calculate_port_from_hash(socket_path: &str) -> u16 {
    let mut hash: u32 = 5381;
    for byte in socket_path.bytes() {
        hash = ((hash << 5).wrapping_add(hash)).wrapping_add(byte as u32);
    }
    // Use ports in range 49152-65535 (dynamic/private range)
    (hash % 15900 + 49152) as u16
}

#[cfg(test)]
pub(crate) mod test_support {
    use super::*;
    use std::time::Duration;

    /// Returns ((server_sender, server_events), (client_sender, client_events)).
    #[cfg(unix)]
    pub fn test_pair() -> ((SocketSender, EventSocket), (SocketSender, EventSocket)) {
        let dir = tempfile::tempdir().unwrap();
        let socket_path = dir.path().join("test.sock");
        let socket_path_str = socket_path.to_str().unwrap().to_string();
        let socket_path_str2 = socket_path_str.clone();

        let server_handle = std::thread::spawn(move || listen(&socket_path_str).unwrap());

        // Small delay to let server start listening
        std::thread::sleep(Duration::from_millis(100));

        let client = connect(&socket_path_str2).unwrap();
        let server = server_handle.join().unwrap();
        // Keep tempdir alive by leaking it (tests are short-lived)
        std::mem::forget(dir);
        (server, client)
    }
}

#[cfg(all(test, unix))]
mod tests {
    use super::test_support::test_pair;
    use super::*;
    use std::time::Duration;

    fn recv(events: &EventSocket) -> Frame {
        events
            .incoming
            .recv_timeout(Duration::from_secs(5))
            .unwrap()
    }

    #[test]
    fn test_send_recv_event() {
        let ((_server_sender, server_events), (client_sender, _client_events)) = test_pair();

        client_sender.send(Message::GetAvailableContent).unwrap();

        let frame = recv(&server_events);
        assert_eq!(frame.request_id, None);
        assert!(matches!(frame.message, Message::GetAvailableContent));
    }

    #[test]
    fn test_request_id_round_trip() {
        let ((server_sender, server_events), (client_sender, client_events)) = test_pair();

        client_sender
            .send_with_id(Some(7), Message::ListCameras)
            .unwrap();
        let request = recv(&server_events);
        assert_eq!(request.request_id, Some(7));

        server_sender
            .send_with_id(request.request_id, Message::CameraList(vec![]))
            .unwrap();
        let response = recv(&client_events);
        assert_eq!(response.request_id, Some(7));
        assert!(matches!(response.message, Message::CameraList(_)));
    }

    #[test]
    fn test_event_frame_omits_request_id_on_the_wire() {
        let json = serde_json::to_string(&Frame::event(Message::Ping)).unwrap();
        assert!(!json.contains("request_id"), "{json}");
        let frame: Frame = serde_json::from_str(r#"{"message":"Ping"}"#).unwrap();
        assert_eq!(frame.request_id, None);
    }

    #[test]
    fn test_call_messages_round_trip() {
        let json = serde_json::to_string(&Message::CallEnd(Some(42))).unwrap();
        assert!(matches!(
            serde_json::from_str::<Message>(&json).unwrap(),
            Message::CallEnd(Some(42))
        ));
        let json = serde_json::to_string(&Message::CallEnded(None)).unwrap();
        assert!(matches!(
            serde_json::from_str::<Message>(&json).unwrap(),
            Message::CallEnded(None)
        ));
    }

    #[test]
    fn test_window_content_round_trip() {
        let serialized = serde_json::to_string(&Content {
            content_type: ContentType::Window,
            id: 42,
        })
        .unwrap();
        let content: Content = serde_json::from_str(&serialized).unwrap();

        assert!(matches!(content.content_type, ContentType::Window));
        assert_eq!(content.id, 42);
    }

    #[test]
    fn test_app_veil_bundle_ids_transport_round_trip() {
        let ((_server_sender, server_events), (client_sender, _client_events)) = test_pair();
        let bundle_ids = vec![
            "com.apple.notificationcenterui".to_string(),
            "com.example.private".to_string(),
        ];

        client_sender
            .send(Message::SetAppVeilBundleIds(bundle_ids.clone()))
            .unwrap();

        match recv(&server_events).message {
            Message::SetAppVeilBundleIds(received) => assert_eq!(received, bundle_ids),
            _ => panic!("expected app veil bundle IDs"),
        }
    }

    #[test]
    fn test_events_and_responses_keep_wire_order() {
        let ((_server_sender, server_events), (client_sender, _client_events)) = test_pair();

        client_sender.send(Message::GetAvailableContent).unwrap();
        client_sender
            .send_with_id(Some(1), Message::ListAudioDevices)
            .unwrap();
        client_sender.send(Message::CallEnd(Some(3))).unwrap();

        assert!(matches!(
            recv(&server_events).message,
            Message::GetAvailableContent
        ));
        let second = recv(&server_events);
        assert_eq!(second.request_id, Some(1));
        assert!(matches!(
            recv(&server_events).message,
            Message::CallEnd(Some(3))
        ));
    }

    #[test]
    fn test_multiple_messages_ordering() {
        let ((_server_sender, server_events), (client_sender, _client_events)) = test_pair();

        for i in 0..10 {
            client_sender.send(Message::CallEnded(Some(i))).unwrap();
        }
        for i in 0..10 {
            match recv(&server_events).message {
                Message::CallEnded(Some(id)) => assert_eq!(id, i),
                other => panic!("unexpected {other:?}"),
            }
        }
    }

    #[test]
    fn test_sender_clone() {
        let ((_server_sender, server_events), (client_sender, _client_events)) = test_pair();

        let clone = client_sender.clone();
        client_sender.send(Message::Ping).unwrap();
        clone.send(Message::GetAvailableContent).unwrap();

        assert!(matches!(recv(&server_events).message, Message::Ping));
        assert!(matches!(
            recv(&server_events).message,
            Message::GetAvailableContent
        ));
    }

    #[test]
    fn test_disconnect_closes_channels() {
        let ((_server_sender, server_events), (client_sender, client_events)) = test_pair();

        drop(client_sender);
        drop(client_events);

        loop {
            match server_events.incoming.recv_timeout(Duration::from_secs(5)) {
                Ok(_) => continue,
                Err(mpsc::RecvTimeoutError::Disconnected) => break,
                Err(mpsc::RecvTimeoutError::Timeout) => {
                    panic!("Timed out waiting for channel to close")
                }
            }
        }
    }

    #[test]
    fn test_dropping_event_socket_unblocks_its_reader() {
        // The reader has no read timeout; drop must still end it (shutdown wakes the read).
        let ((_server_sender, server_events), (_client_sender, mut client_events)) = test_pair();
        let incoming = client_events.take_incoming();
        drop(client_events);
        assert!(matches!(
            incoming.recv_timeout(Duration::from_secs(5)),
            Err(mpsc::RecvTimeoutError::Disconnected)
        ));
        drop(server_events);
    }

    #[test]
    fn test_slow_writer_does_not_desync_framing() {
        // A frame written in pieces with pauses (formerly longer than the 1 s read timeout)
        // must still decode.
        let ((server_sender, _server_events), (_client_sender, client_events)) = test_pair();
        let bytes = encode_frame(&Frame::event(Message::CallEnded(Some(5)))).unwrap();
        let (head, tail) = bytes.split_at(3);
        {
            let mut stream = server_sender.stream.lock().unwrap();
            stream.write_all(head).unwrap();
        }
        std::thread::sleep(Duration::from_millis(1300));
        {
            let mut stream = server_sender.stream.lock().unwrap();
            stream.write_all(tail).unwrap();
        }
        server_sender.send(Message::Ping).unwrap();
        assert!(matches!(
            recv(&client_events).message,
            Message::CallEnded(Some(5))
        ));
        assert!(matches!(recv(&client_events).message, Message::Ping));
    }

    #[test]
    fn test_undecodable_frame_is_skipped() {
        let ((server_sender, _server_events), (_client_sender, client_events)) = test_pair();
        {
            let payload = br#"{"message":"NoSuchVariant"}"#;
            let mut stream = server_sender.stream.lock().unwrap();
            stream
                .write_all(&(payload.len() as u64).to_le_bytes())
                .unwrap();
            stream.write_all(payload).unwrap();
        }
        server_sender.send(Message::Ping).unwrap();
        assert!(matches!(recv(&client_events).message, Message::Ping));
    }

    #[test]
    fn test_oversized_or_non_utf8_frame_closes_without_panic() {
        let ((server_sender, _server_events), (_client_sender, client_events)) = test_pair();
        {
            let mut stream = server_sender.stream.lock().unwrap();
            // Non-UTF-8 payload: skipped as a decode error, not a panic.
            stream.write_all(&2u64.to_le_bytes()).unwrap();
            stream.write_all(&[0xff, 0xfe]).unwrap();
        }
        server_sender.send(Message::Ping).unwrap();
        assert!(matches!(recv(&client_events).message, Message::Ping));
        {
            let mut stream = server_sender.stream.lock().unwrap();
            stream
                .write_all(&(MAX_FRAME_BYTES + 1).to_le_bytes())
                .unwrap();
        }
        assert!(matches!(
            client_events.incoming.recv_timeout(Duration::from_secs(5)),
            Err(mpsc::RecvTimeoutError::Disconnected)
        ));
    }
}
